# Part 1 - Data Preprocessing



In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
import os
os.getcwd()

'F:\\classes\\Python_learning\\Notebooks\\ANN'

In [3]:
os.chdir("F:\\dataset_projects\\ANN")

In [4]:
# Importing the dataset
dataset = pd.read_csv('Churn_Modelling_1.csv')
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [5]:
dataset.shape

(9990, 14)

In [6]:
dataset.describe()

RowNumber    CustomerId  CreditScore          Age       Tenure  \
count   9990.000000  9.990000e+03  9990.000000  9990.000000  9990.000000   
mean    5005.232432  1.569090e+07   650.517417    38.923323     5.010911   
std     2884.452038  7.194938e+04    96.675835    10.489822     2.891847   
min        1.000000  1.556570e+07   350.000000    18.000000     0.000000   
25%     2508.250000  1.562834e+07   584.000000    32.000000     3.000000   
50%     5005.500000  1.569071e+07   652.000000    37.000000     5.000000   
75%     7502.750000  1.575323e+07   718.000000    44.000000     7.000000   
max    10000.000000  1.581569e+07   850.000000    92.000000    10.000000   

             Balance  NumOfProducts    HasCrCard  IsActiveMember  \
count    9990.000000    9990.000000  9990.000000     9990.000000   
mean    76498.012142       1.529730     0.705506        0.515115   
std     62385.756190       0.581239     0.455838        0.499796   
min         0.000000       1.000000     0.000000        0.000000   
25%         0.000000       1.000000     0.000000        0.000000   
50%     97221.520000       1.000000     1.000000        1.000000   
75%    127641.417500       2.000000     1.000000        1.000000   
max    250898.090000       4.000000     1.000000        1.000000   

       EstimatedSalary       Exited  
count      9990.000000  9990.000000  
mean     100088.744161     0.203303  
std       57515.531698     0.402476  
min          11.580000     0.000000  
25%       51012.472500     0.000000  
50%      100185.240000     0.000000  
75%      149395.882500     0.000000  
max      199992.480000     1.000000

In [7]:
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values


In [8]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [9]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [10]:
# # Encoding categorical data
# from sklearn.preprocessing import LabelEncoder, OneHotEncoder
# labelencoder_X_1 = LabelEncoder()
# X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
# labelencoder_X_2 = LabelEncoder()
# X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
# onehotencoder = OneHotEncoder(categorical_features = [1])
# X = onehotencoder.fit_transform(X).toarray()
# X = X[:, 1:]


In [10]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder


In [11]:
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
X[:, 1]

array([0, 2, 0, ..., 0, 1, 0], dtype=object)

In [12]:
X[:, 1][0:10]

array([0, 2, 0, 0, 2, 2, 0, 1, 0, 0], dtype=object)

In [13]:
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
X[:, 2]

array([0, 0, 0, ..., 0, 1, 0], dtype=object)

In [14]:
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [15]:
X[0:3]

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 6.1900000e+02,
        0.0000000e+00, 4.2000000e+01, 2.0000000e+00, 0.0000000e+00,
        1.0000000e+00, 1.0000000e+00, 1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 6.0800000e+02,
        0.0000000e+00, 4.1000000e+01, 1.0000000e+00, 8.3807860e+04,
        1.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.1254258e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 5.0200000e+02,
        0.0000000e+00, 4.2000000e+01, 8.0000000e+00, 1.5966080e+05,
        3.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.1393157e+05]])

In [16]:
X = X[:, 1:]
X

array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 1.0000000e+00, 6.0800000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [0.0000000e+00, 0.0000000e+00, 5.0200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 7.0900000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [1.0000000e+00, 0.0000000e+00, 7.7200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [0.0000000e+00, 0.0000000e+00, 7.9200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [17]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [18]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


In [19]:
X_train

array([[ 1.72171011, -0.57908406,  1.08838629, ..., -1.53695195,
         0.9730848 , -0.86368396],
       [-0.58081787,  1.72686502,  0.72771878, ..., -1.53695195,
         0.9730848 ,  0.30350613],
       [-0.58081787, -0.57908406, -0.0245306 , ...,  0.65063843,
         0.9730848 ,  1.55252861],
       ...,
       [-0.58081787, -0.57908406, -0.22032153, ...,  0.65063843,
         0.9730848 , -1.45374831],
       [-0.58081787,  1.72686502,  0.57314699, ...,  0.65063843,
         0.9730848 , -1.31558336],
       [-0.58081787, -0.57908406, -0.01422581, ...,  0.65063843,
         0.9730848 , -0.51456556]])

# Part 2 - Now let's make the ANN!

In [20]:

# Part 2 - Now let's make the ANN!

# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

F:\life\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [21]:

# Initialising the ANN
classifier = Sequential()


In [22]:
# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))



Instructions for updating:
Colocations handled automatically by placer.


In [23]:

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])


In [24]:
classifier.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 6)                 72        
_________________________________________________________________
dense_2 (Dense)              (None, 6)                 42        
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 7         
Total params: 121
Trainable params: 121
Non-trainable params: 0
_________________________________________________________________


In [25]:

# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)


Instructions for updating:
Use tf.cast instead.
Epoch 1/100
7992/7992 [==============================] - 1s 155us/step - loss: 0.4915 - acc: 0.7963 1s - loss: 0.6174 -
Epoch 2/100
7992/7992 [==============================] - 1s 108us/step - loss: 0.4161 - acc: 0.8173
Epoch 3/100
7992/7992 [==============================] - 1s 108us/step - loss: 0.4039 - acc: 0.8233
Epoch 4/100
7992/7992 [==============================] - 1s 111us/step - loss: 0.3930 - acc: 0.8256
Epoch 5/100
7992/7992 [==============================] - 1s 108us/step - loss: 0.3846 - acc: 0.8268
Epoch 6/100
7992/7992 [==============================] - 1s 106us/step - loss: 0.3777 - acc: 0.8305
Epoch 7/100
7992/7992 [==============================] - 1s 108us/step - loss: 0.3735 - acc: 0.8412
Epoch 8/100
7992/7992 [==============================] - 1s 123us/step - loss: 0.3688 - acc: 0.8472
Epoch 9/100
7992/7992 [==============================] - 1s 122us/step - loss: 0.3664 - acc: 0.8486
Epoch 10/100
7992/7992 [========

7992/7992 [==============================] - 1s 97us/step - loss: 0.3390 - acc: 0.8574: 0s - loss: 0.3333 - acc
Epoch 79/100
7992/7992 [==============================] - 1s 104us/step - loss: 0.3388 - acc: 0.8584
Epoch 80/100
7992/7992 [==============================] - 1s 103us/step - loss: 0.3373 - acc: 0.8607
Epoch 81/100
7992/7992 [==============================] - 1s 130us/step - loss: 0.3383 - acc: 0.8607 0s - loss: 0.3382 - acc
Epoch 82/100
7992/7992 [==============================] - 1s 106us/step - loss: 0.3382 - acc: 0.8600
Epoch 83/100
7992/7992 [==============================] - 1s 108us/step - loss: 0.3386 - acc: 0.8589
Epoch 84/100
7992/7992 [==============================] - 1s 106us/step - loss: 0.3379 - acc: 0.8607
Epoch 85/100
7992/7992 [==============================] - 1s 106us/step - loss: 0.3378 - acc: 0.8604
Epoch 86/100
7992/7992 [==============================] - 1s 101us/step - loss: 0.3377 - acc: 0.8612
Epoch 87/100
7992/7992 [==============================] 

In [26]:
# Part 3 - Making predictions and evaluating the model

# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred

array([[0.915893  ],
       [0.11415115],
       [0.04823163],
       ...,
       [0.2917756 ],
       [0.05188147],
       [0.5161404 ]], dtype=float32)

In [27]:
y_pred = (y_pred > 0.5)
y_pred

array([[ True],
       [False],
       [False],
       ...,
       [False],
       [False],
       [ True]])

In [28]:
y_pred[0:10]

array([[ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False]])

# Part 3 Predicting a single new observation

In [29]:
# Predicting a single new observation
#"""Predict if the customer with the following informations will leave the bank:
#Geography: France
#Credit Score: 600
# Gender: Male
# Age: 40
# Tenure: 3
# Balance: 60000
# Number of Products: 2
# Has Credit Card: Yes
# Is Active Member: Yes
# Estimated Salary: 50000"""

In [ ]:
# CreditScore	Geography	Gender	Age	Tenure	Balance	NumOfProducts	HasCrCard	IsActiveMember	EstimatedSalary	Exited
# 549	Spain	Female	24	9	0	2	1	1	14406.41	0
# 722	Spain	Female	29	9	0	2	1	1	142033.07	0
# 788	France	Female	33	5	0	2	0	0	116978.19	0
# 581	Germany	Female	34	1	101633.04	1	1	0	110431.51	0
# 735	France	Female	21	1	178718.19	2	1	0	22388	0
										
										
# 735	France	Female	21	1	178718.19	2	1	0	22388	0
# 687	Spain	Female	44	7	0	3	1	0	155853.52	1
# 693	Germany	Female	41	9	181461.48	3	1	1	187929.43	1
# 553	Spain	Male	47	3	116528.15	1	0	0	145704.19	1
# 662	France	Female	32	4	133950.37	1	1	1	48725.68	1
# 621	Spain	Male	53	9	170491.84	1	1	0	35588.07	1
										
# 601	France	Female	43	8	0	3	0	1	110916.15	1


In [32]:
new_prediction_1 = classifier.predict(sc.transform(np.array([[549, 0.0 ,0, 0,24,9, 0, 2, 1, 1, 14406.41]])))

new_prediction_1

array([[1.]], dtype=float32)

In [33]:
new_prediction_1 = (new_prediction_1 > 0.5)
new_prediction_1

array([[ True]])

In [ ]:

# # Making the Confusion Matrix
# from sklearn.metrics import confusion_matrix
# cm = confusion_matrix(y_test, new_prediction_1)

In [36]:
new_prediction_2 = classifier.predict(sc.transform(np.array([[649, 0.1 ,0, 0,43,8, 0, 3, 0, 1, 110916.15]])))

new_prediction_2

array([[1.]], dtype=float32)

In [37]:
new_prediction_2 = (new_prediction_1 > 0.5)
new_prediction_2

array([[ True]])

In [38]:
# 662	France	Female	32	4	133950.37	1	1	1	48725.68	1
new_prediction_2 = classifier.predict(sc.transform(np.array([[62, 0.1 ,0, 0,32,4, 133950.37, 1, 1, 1, 18725.68])))

new_prediction_2

SyntaxError: invalid syntax (<ipython-input-38-cbdd21803a7a>, line 2)

In [ ]:



# Predicting a single new observation
#"""Predict if the customer with the following informations will leave the bank:
#Geography: Ger
#Credit Score: 747
# Gender: Male
# Age: 36
# Tenure: 8
# Balance: 102603.3
# Number of Products: 2
# Has Credit Card: Yes
# Is Active Member: Yes
# Estimated Salary: 182603"""

In [29]:
new_prediction_2 = classifier.predict(sc.transform(np.array([[1.0, 0, 747, 1, 36, 8, 102603, 2, 1, 1, 180693]])))
new_prediction_2 = (new_prediction_2 > 0.5)
new_prediction_2

array([[False]])

In [32]:
new_prediction_3 = classifier.predict(sc.transform(np.array([[0.0, 0, 655, 1, 41, 8, 125562, 1, 0, 0, 164040]])))
new_prediction_3 = (new_prediction_3 > 0.5)
new_prediction_3

array([[False]])

In [33]:
new_prediction_= classifier.predict(sc.transform(np.array([[0.0, 0, 698, 1, 44, 10, 116364.4, 2, 1, 0, 198059.16]])))
new_prediction_ = (new_prediction_3 > 0.5)
new_prediction_3

array([[False]])

In [37]:
new_prediction_5 = classifier.predict(sc.transform(np.array([[0.0, 0,586, 0, 54, 4, 154864.4, 2, 1, 1, 248476.16]])))
new_prediction_5


array([[0.49430588]], dtype=float32)

In [38]:
new_prediction_5 = (new_prediction_5 > 0.5)
new_prediction_5

array([[False]])

In [46]:
new_prediction_6 = classifier.predict(sc.transform(np.array([[0.00,0, 683, 1, 40, 4, 95053.1, 1, 1, 1, 116816.54]])))
new_prediction_6

array([[0.10806476]], dtype=float32)

In [47]:
new_prediction_6 = (new_prediction_5 > 0.5)
new_prediction_6

array([[False]])

In [ ]:

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [ ]:
cm

In [ ]:
# accuracy =(TN+TP)/(TN+TP+FN+FP)

In [ ]:
TN= 1503
TP= 219
total =2000
acc =(TN+TP)/2000
acc